### ISSUE TITLE
nginx_exporter el6 issues

### ISSUE THREAD

**Issue by akurach** [lest/prometheus-rpm#103]
Hello, there are some issues with nginx_exporter on el6 OS. 

1. daemonize pkg is needed and its better to add it in req list
2. in /etc/init.d/nginx_exporter 
line 33 u have to change ${EXPORTER_ARGS} to ${NGINX_EXPORTER_OPTS}

**Comment by zoonage** [comment]
@lest can you assign this issue to me so I don't forget about it? I should have some time to fix it as it's a public holiday in the UK this weekend

**Comment by karlism** [comment]
Closing as CentOS 6 support [has been deprecated](https://github.com/lest/prometheus-rpm/pull/304)
