### ISSUE TITLE
openstack exporter ?

### ISSUE THREAD

**Issue by tureba** [lest/prometheus-rpm#110]
Hi,

Any plans on adding openstack exporter to the repo?

Thanks,
Arthur

**Comment by zoonage** [comment]
Hi @tureba can you provide a URL to the repo?

**Comment by tureba** [comment]
Hi
Sure, we've been using https://github.com/Linaro/openstack-exporter successfully.

**Comment by karlism** [comment]
@tureba, are you still interested in this?

This one seems to be a better option:
https://github.com/openstack-exporter/openstack-exporter

Last commit less than a month ago vs more than one year ago for the Linaro one

**Comment by tureba** [comment]
Oh, that looks promising. I think I'd checked it out last year, but something was off then; don't remember what.
Nowadays, it looks like the best option, indeed.

**Comment by karlism** [comment]
@tureba, I've just added OpenStack exporter, please test it as I have no access to OpenStack to test it myself.

**Comment by tureba** [comment]
Works well, thanks!
