### ISSUE TITLE
Bump limits in unit files?

### ISSUE THREAD

**Issue by britcey** [lest/prometheus-rpm#144]
I find myself adding override files for several of these packages (blackbox, snmp & prometheus itself) - the default file limit of 4096 is just too low.

Should we just add 

LimitNOFILE=65536

(or some other value) to the unit files by default?

**Comment by karlism** [comment]
@britcey, agreed, and Alertmanager too.
Are you sure you're hitting hard limits, as `process_open_fds` metrics usually report soft limit, which is 1024 by default. We've had to increase soft limits for our Alertmanager and Prometheus instances by increasing it to 3072 like this:
```
LimitNOFILE=3072:4096
```

**Comment by britcey** [comment]
I suspect you're right & I hit the soft limit:

  `fd_limits="(soft=1024, hard=4096)"`

but after setting just LimitNOFILE=8192, it adjusted both:

   `fd_limits="(soft=8192, hard=8192)"`

Any particular reason to adjust the soft limit separately?

And do we have any feel for what's a good figure?

**Comment by britcey** [comment]
I asked on #prometheus-dev & bbrazil replied:

> I'd set it to a million across the entire system, and not worry about it

So let's say 65536 across the board?  Quite high without being unlimited.

**Comment by karlism** [comment]
65536 sounds fine to me, million - not so much. These limits are there for a reason after all, and any system would be dead long before reaching them.

**Comment by britcey** [comment]
Agreed;  I'll add

LimitNOFILE=65536

to to the prometheus, alertmanager, blackbox_exporter & snmp_exporter unit files - any others?  

I imagine any proxy-style exporters (like blackbox & snmp) should have it - I'm less familiar with the other exporters we package up but I think the rest are one-to-one style exporters.

**Comment by britcey** [comment]
Closing this out.
