### ISSUE TITLE
Init script should exit with value > 0 when 'status' action is not running

### ISSUE THREAD

**Issue by travis-bear** [lest/prometheus-rpm#151]
Condition: node_exporter is not running
User action: user calls the `status` action of the init script
Expected: init script exits with value > 0
Actual: init script exits with value 0

Example:

```
[root@aort-alerta-s3 ~]# /etc/init.d/node_exporter status
node_exporter is not running
[root@aort-alerta-s3 ~]# echo $?
0
```

The exit value of this script is consulted by infrastructure tooling (e.g. Chef) to determine if the service needs to be restarted, so this bug interferes with automated lifecycle management.

I don't expect this to be a controversial change, but here is the references to the LSB spec just in case:

http://refspecs.linuxbase.org/LSB_3.0.0/LSB-PDA/LSB-PDA/iniscrptact.html

**Comment by timhughes** [comment]
Same issue with puppet http://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html
