### ISSUE TITLE
Please provide centos 8 packages

### ISSUE THREAD

**Issue by ruben-herold** [lest/prometheus-rpm#152]
hi,

centos 8 is now the current centos release. Could you please also provide packages for centos 8

**Comment by bjorntj** [comment]
CentOS 8 packages would be nice.. :)

**Comment by Atoms** [comment]
is there some update for centos8 ? :)

**Comment by jstallard** [comment]
I have submitted a PR to zoonage, whose docker images are used for building these RPMs: https://github.com/zoonage/centos-rpm-builder-docker/pull/4

If/when that is accepted and the centos8 build images are uploaded to quay.io, I can open a PR here w/ the changes necessary to build. Here's a draft PR w/ the changes-to-be: https://github.com/lest/prometheus-rpm/pull/193

**Comment by lest** [comment]
Some packages are now available for CentOS 8:

- node_exporter
- mysqld_exporter
- redis_exporter
- haproxy_exporter
- kafka_exporter
- nginx_exporter
- ssl_exporter
- bind_exporter

Keeping this issue open until all packages are ready for CentOS8.

**Comment by bjorntj** [comment]
Any progress on this?

**Comment by karlism** [comment]
@lest, is there anything stopping us from building all packages for CentOS 8 now? I've just tried building `prometheus2` package for it and it seemed to work just fine:
```yaml
PACKAGES8 = prometheus2
8: $(PACKAGES8)
$(PACKAGES8):
	docker run --rm \
		-v ${PWD}/$@:/rpmbuild/SOURCES \
		-v ${PWD}/_dist8:/rpmbuild/RPMS/x86_64 \
		-v ${PWD}/_dist8:/rpmbuild/RPMS/noarch \
		lest/centos-rpm-builder:8 \
		build-spec SOURCES/$@.spec
```

**Comment by lest** [comment]
@karlism Thank you for checking it out. I think nothing stops us from building all CentOS 7 packages for CentOS 8 as well really. Please feel free to update `Makefile`, we'll also need to update `.travis.yml` to parallelize those additional builds.
