### ISSUE TITLE
Add nginx-vts-exporter

### ISSUE THREAD

**Issue by patsevanton** [lest/prometheus-rpm#160]
May be add https://github.com/hnlq715/nginx-vts-exporter ?

nginx-vts-exporter  - Simple server that scrapes Nginx vts stats and exports them via HTTP for Prometheus consumption

**Comment by ruben-herold** [comment]
Think you can close this cause not needed
In recent versions of nginx-vts it can do it alone:

https://github.com/vozlt/nginx-module-vts

"/status/format/prometheus

    If you request /status/format/prometheus, will respond with a prometheus document containing the current activity data. "

**Comment by patsevanton** [comment]
Ok
