### ISSUE TITLE
prometheus2 SPEC file tsdb build error

### ISSUE THREAD

**Issue by crunchytyler** [lest/prometheus-rpm#170]
Hello,

I believe there is an issue with the prometheus2 SPEC file [here](https://github.com/lest/prometheus-rpm/blob/master/prometheus2/prometheus2.spec) that causes builds to fail with the following error:
`install: omitting directory 'tsdb'`

It appears to be due to the following line (34):
`install -D -m 755 tsdb %{buildroot}%{_bindir}/tsdb`

This line is pointing to a sub-directory within the prometheus source where the tsdb binary is located, and not pointing to the actual binary within that tsdb sub-directory.

A proposed fix would look something like this:
`install -D -m 755 tsdb/tsdb %{buildroot}%{_bindir}/tsdb`

Prometheus version/tag build that I tested against: v2.13.1

Very respectfully,
Tyler

**Comment by britcey** [comment]
Hi Tyler,

That's not a "real" spec file in the sense it's made for building prometheus from scratch - it's used to package up the released binaries:

https://github.com/prometheus/prometheus/releases

'tsdb' is indeed in the same directory as 'prometheus' and 'promtool' in the release tarball.

That spec file won't work for building prometheus from scratch.

**Comment by britcey** [comment]
@lest I think this can be closed.

**Comment by britcey** [comment]
Closing this out.
