### ISSUE TITLE
Collaborator access to repository

### ISSUE THREAD

**Issue by karlism** [lest/prometheus-rpm#177]
@lest, can you please give me and @britcey collaborator access to `prometheus-rpm` repository so that we can push updates and merge requests? Sometimes it takes you quite some time to approve even minor changes, like version updates and we could probably help you with that.

**Comment by britcey** [comment]
I was going to broach that subject as well;  you'd still be fully in control of getting the packages to package cloud, etc. but we should be able to ease some of your burden.

**Comment by lest** [comment]
Thank you for your numerous contributions! I'd really appreciate your further help. I've given you both access to the repository.
