### ISSUE TITLE
postgres_exporter outdated on packagecloud.io

### ISSUE THREAD

**Issue by david-ecc** [lest/prometheus-rpm#192]
On packagecloud.io the newest version for el7 is 0.4.7: https://packagecloud.io/app/prometheus-rpm/release/search?q=postgres_exporter

Latest version in .spec-file is 0.8.0:
https://github.com/lest/prometheus-rpm/blob/master/postgres_exporter/postgres_exporter.spec

Please update the packages on packagecloud.io

**Comment by karlism** [comment]
Thanks for reporting this issue, fixed by https://github.com/lest/prometheus-rpm/pull/196
