### ISSUE TITLE
node_exporter probably should be run as root

### ISSUE THREAD

**Issue by kinghrothgar** [lest/prometheus-rpm#2]
So if I am not mistaken, about 50% of node_exporter's collectors (sockstat , netstat, hwmon, ext.) require it running as root. The service file has it running as the prometheus user. Although it would be nice to have it not run as root, I think it really has too.

**Comment by lest** [comment]
There are no mentions in node_exporter's README about running it as root. I'm not sure that collectors that you mentioned require running as root. For example, the sockstat collector reads `/proc/net/sockstat` which is readable for all users, the same is for the netstat collector that reads `/proc/net/netstat`.

Did you encounter any specific errors or missing data when running node_exporter as a non-root user?

**Comment by kinghrothgar** [comment]
```
ERROR: sockstat collector failed after 0.000030s: couldn't get sockstats: open /proc/net/sockstat: permission denied
ERROR: netstat collector failed after 0.000100s: couldn't get netstats: open /proc/net/netstat: permission denied
ERROR: hwmon collector failed after 0.000022s: open /sys/class/hwmon: permission denied
```

So at least on CentOS 7, /sys/class is 700, so hwmon definitely requires root. I'm confused on the other ones though as the permissions are 444. However running as root fixes the errors. I guess I should open an issue on node_exporter to see if this is expected.

**Comment by lest** [comment]
This is weird. I have the latest CentOS 7 running but not on bare-metal, however. That's why there is no `/sys/class/hwmon` present but `/sys/class` directory permissions are 0755.

A possible difference can be in SELinux settings since I don't have it enabled.

**Comment by kinghrothgar** [comment]
It's because I'm running a stupid OVH custom kernel (not by choice).  Closing, Thanks for the help.
