### ISSUE TITLE
How to go about adding golang dependency?

### ISSUE THREAD

**Issue by schmidtw** [lest/prometheus-rpm#205]
Hello,

I've added support for [`dnsmasq_exporter`](https://github.com/schmidtw/prometheus-rpm/commit/1d7ff351de6400ff34a8634ab233f27cd8b0c93e) but I need the docker images to include `epel-release` or some other way to acquire the build dependency `golang`.

I've been able to test that with this one additional repo enabled, the build works. via changing:
[`build-spec SOURCES/autogen_${PACKAGE}.spec`](https://github.com/lest/prometheus-rpm/blob/master/Makefile#L83) to:
```
/bin/bash -c '/usr/bin/yum install --verbose -y epel-release && build-spec SOURCES/autogen_${PACKAGE}.spec'
```
How would you suggest proceeding?

Thanks,
Wes

**Comment by karlism** [comment]
I don't think this is possible by using existing templates, but you can create custom spec file, like https://github.com/lest/prometheus-rpm/blob/master/prometheus2/prometheus2.spec, and specify `epel-release` as `BuildRequires` parameter.
Bet we build packages from pre-built binaries, so best course of action would be to ask `dnsmasq_exporter` developers if they can provide them.
