### ISSUE TITLE
snmp.yml is missing from snmp_exporter

### ISSUE THREAD

**Issue by scttfrdmn** [lest/prometheus-rpm#22]
The snmp.yml file is needed for snmp_exporter to run.

I would be happy to submit a pull request but I am not sure where you would want to put the file.

-Scott

**Comment by lest** [comment]
Hi Scott,

I think we can put it to `/etc/prometheus/snmp.yml` similar to how we have `blackbox.yml` copied to `/etc/prometheus/blackbox.yml`:

https://github.com/lest/prometheus-rpm/blob/master/blackbox_exporter/blackbox_exporter.spec

Thank you!

Cheers,
Sergey

**Comment by lest** [comment]
Fixed in 94a4a3127af2b35af9b8aebd6297d2707758507d.
