### ISSUE TITLE
Centos 7 Node_exporter package systemd file issue

### ISSUE THREAD

**Issue by muralibabu** [lest/prometheus-rpm#231]
Hi

I have installed node_exporter-0.18.1-1.el7.centos.x86_64 rpm on centos 7
After install systemd ("/usr/lib/systemd/system/node_exporter.service") file created with different 'ExecStart' Argument and EnvironmentFile needs change.

Please look into this and compile and update new RPM for centos7.

Thanks
Murali

Host operating system: output of uname -a
Linux example.com 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

node_exporter version: output of node_exporter --version
node_exporter, version 0.18.1 (branch: HEAD, revision: 3db7773)
build user: root@b50852a1acba
build date: 20190604-16:41:18
go version: go1.12.5

node_exporter command line flags
/usr/bin/node_exporter --collector.systemd

Are you running node_exporter in Docker?
NO

What did you do that produced an error?
Installed node_exporter-0.18.1-1.el7.centos.x86_64 rpm

What did you expect to see?
EnvironmentFile=/etc/default/node_exporter
User=prometheus
ExecStart=/usr/bin/node_exporter $EXPORTER_ARGS

What did you see instead?
EnvironmentFile=-/etc/default/node_exporter
User=prometheus
ExecStart=/usr/bin/node_exporter $NODE_EXPORTER_OPTS

**Comment by karlism** [comment]
@muralibabu, why did you expect `$EXPORTER_ARGS` to be there?

It's true that packages build for CentOS 6 have different variable than ones that are built for CentOS 7/8 (https://github.com/lest/prometheus-rpm/pull/80). We do not want to change that as that would be braking change for anyone who has these packages already installed on their CentOS 6 systems, and considering that CentOS 6 is reaching EOL in November this year, we are probably gonna drop CentOS 6 support soon anyway.

**Comment by karlism** [comment]
All packages in this repo have consistent naming `${NAME}_OPTS`, see this for an example:
```
$ cat /etc/default/* | grep OPTS
NODE_EXPORTER_OPTS="--collector.textfile.directory=/var/lib/node_exporter/textfile_collector --collector.ntp --collector.processes --web.listen-address=xx.xx.xx.xx:9100"
PROMETHEUS_OPTS='--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus/data --storage.tsdb.retention.time=30d --web.enable-admin-api --web.page-title=hostname --web.external-url=http://hostname.example.com:9090'
PROMTAIL_OPTS="--config.file=/etc/promtail/promtail.yml --log.level=warn"
THANOS_COMPACT_OPTS='--data-dir=/var/lib/thanos/compact --http-address=0.0.0.0:19191'
THANOS_QUERY_OPTS='--http-address=0.0.0.0:19192 --grpc-address=0.0.0.0:19092 --store=localhost:10901'
THANOS_RULE_OPTS='--data-dir=/var/lib/thanos/rule --http-address=0.0.0.0:19902 --grpc-address=0.0.0.0:19901 --rule-file=/etc/prometheus/thanos_alerts.yml --query=localhost:19192'
THANOS_SIDECAR_OPTS='--prometheus.url=http://localhost:9090'
THANOS_STORE_OPTS='--data-dir=/var/lib/thanos/store --http-address=0.0.0.0:19191 --grpc-address=0.0.0.0:19090'
```

**Comment by muralibabu** [comment]
Got it.
Please help below issue,
Systemd file has EnvironmentFile=-/etc/default/node_exporter which should be only
EnvironmentFile=/etc/default/node_exporter.

**Comment by karlism** [comment]
Quoting systemd `EnvironmentFile` documentation:
> The argument passed should be an absolute filename or wildcard expression, optionally prefixed with "-", which indicates that if the file does not exist, it will not be read and no error or warning message is logged.

Why do you think that `-` should be removed?

**Comment by muralibabu** [comment]
Understand the meaning for the '-' in systemd. Thanks.
