### ISSUE TITLE
Exporters for Red Hat and CentOS 6

### ISSUE THREAD

**Issue by finkr** [lest/prometheus-rpm#30]
Hello,

We would like to use Prometheus to monitor ou servers, which also has some Red Hat and CentOS 6.

We wonder if you plan to add RHEL6 / CentOS 6 packages for client side exporter (especially  node_exporter, procfs, pushgateway...)

Thanks

**Comment by finkr** [comment]
For your information, we have successfully compiled and tested node_exporter 0.15.0 with Go 1.10 on RHEL 6.6

**Comment by lest** [comment]
Hi @finkr,

I don't have any servers running Red Hat or CentOS 6, so I don't have enough motivation in supporting them. However, I will welcome contributions adding CentOS 6 support to package specs.

Cheers,
Sergey

**Comment by finkr** [comment]
For those who need to monitor RHEL/CentOS6 [ or any linux distribution], you can download a statically compiled binary of node-exporter (and other exporters) directly from  Prometheus Download page:
https://prometheus.io/download/

Make sure to click on "Release notes" to download the most appropriate binary for your Linux variant (i386, x86_64 ...).

This is not an RPM, you have to deploy the file (and SystemV / SystemD script) "manually" (or create a RPM file with that binary).

**Comment by zoonage** [comment]
@finkr I've put in a PR to add support for Centos6 (and Centos5 as well, however they aren't pushed to the el5 repos)
