### ISSUE TITLE
CentOS 6 EoL

### ISSUE THREAD

**Issue by karlism** [lest/prometheus-rpm#302]
@lest & @britcey, CentOS 6 has reached EoL, I suggest we should also drop support and stop building new packages for it, what's your opinion on that?

**Comment by lest** [comment]
I agree with dropping support.

**Comment by karlism** [comment]
It's actually not even an option as CentOS 6 builds [are already failing](https://travis-ci.org/github/lest/prometheus-rpm/jobs/747373013#L276).
I will try to remove CentOS 6 today.
