### ISSUE TITLE
[discussion] Templatising common scripts 

### ISSUE THREAD

**Issue by zoonage** [lest/prometheus-rpm#39]

**Comment by zoonage** [comment]
Is it worth creating templates for the systemd unit files, RPM spec files, and sysv unit scripts to remove a lot of the boiler plate?

My proposition would be have have a YAML file for each RPM that contains template values to populate common fields of common files.

This YAML confit could be extended to include custom commands for the section. To do this I think using blocks would be sufficient.
```YAML
preinst: |
    Run this command
    Run second command
```

This would simplify creating new RPMs, obviously we should allow this method to be overruled (maybe by specifying an override for a file in the configuration)

Thoughts, improvements and criticisms?

**Comment by lest** [comment]
Closing as https://github.com/lest/prometheus-rpm/pull/40 was merged. Thank you!
