### ISSUE TITLE
Move of blackbox_exporter to auto generated package lost capabilities config

### ISSUE THREAD

**Issue by britcey** [lest/prometheus-rpm#400]
@karlism - the old blackbox_exporter.spec had:

%caps(cap_net_raw=ep) %{_bindir}/%{name}

under the %files section.

which set CAP_NET_RAW on blackbox_exporter, which is needed to send ICMP as non-root.

That has been lost with the move to auto generated package (and just bit me hard in a production update).

Do we want to add another static default context?  We could probably torture additional_sources to accomplish that otherwise.

**Comment by karlism** [comment]
@britcey, `additional_sources` is suited for this task, I guess, so I've added new parameter `caps`. Please check in about 10-15 minutes when updated Blackbox Exporter package will be uploaded to repository to see if that has fixed your issue.

**Comment by britcey** [comment]
That change works as intended.
