### ISSUE TITLE
Change repo elasticsearch_exporter

### ISSUE THREAD

**Issue by sasah** [lest/prometheus-rpm#425]
https://github.com/prometheus-community/elasticsearch_exporter

**Comment by karlism** [comment]
We should probably move this exporter to templating too. Does this exporter provide any benefits comparing to [ES Prometheus plugin](https://github.com/vvanholl/elasticsearch-prometheus-exporter)?

**Comment by sasah** [comment]
https://github.com/vvanholl/elasticsearch-prometheus-exporter - this is an internal plugin
