### ISSUE TITLE
alertmanager out-of-date

### ISSUE THREAD

**Issue by haraldkoch** [lest/prometheus-rpm#433]
Alertmanager 0.22.2 was released on 2021-06-01:

https://github.com/prometheus/alertmanager/releases/tag/v0.22.2

**Comment by karlism** [comment]
Alertmanager has been updated to latest version, note that there is breaking change as some service parameters have been moved from systemd service file to `/etc/default/alertmanager` and you might need to adjust that file manually in case if you had previously overridden any of the defaults.
