### ISSUE TITLE
Looks like the node_exporter folder's contents got deleted?

### ISSUE THREAD

**Issue by crunchyjohn** [lest/prometheus-rpm#48]
Hello,

I'm just reporting that node_exporter appears to have had its specfile and service file deleted.  Looking at the tree, it appears to be from a bad merge and possibly unintentional.  Can that be fixed?

Thanks!

**Comment by zoonage** [comment]
Hi @crunchyjohn this is part of the change for #40. This was part of a move towards a way to more easily manage this repository by templating these files, especially when trying to support CentOS 6.

The node_exporter RPM is now generated in two parts. (same with all auto generated RPMs)

1. The templating tool is run that reads the config in `templating.yaml` and uses the templates in `templates/` to generate the appropriate `autogen_*` files
2. The rpm building docker container then has these files mapped into the container to use whilst building the RPM.

This can be triggered by running `make autogen` or `make node_exporter`.

Hopefully that helps clarify where the files have gone.

**Comment by crunchyjohn** [comment]
Thanks!
