### ISSUE TITLE
mtail package is a gzip instead of an executable

### ISSUE THREAD

**Issue by matthiasantierens** [lest/prometheus-rpm#484]
I installed rc44 and rc47. When I did `file` on those 'bins', it told me that it was a zip. 

I renamed mtail to tmail.gz.tar and unzipped them and got the binary.

**Comment by matthiasantierens** [comment]
I want to fix it but not sure where to look for this. The spec file looks fine to me. 
@karlism Can you give me a pointer?

**Comment by karlism** [comment]
@matthiasantierens, can you please check in about 10-15 minutes if https://github.com/lest/prometheus-rpm/pull/485 has resolved this issue?

**Comment by matthiasantierens** [comment]
@karlism It works! Thank you!
