### ISSUE TITLE
Node exporter does not read defaults file

### ISSUE THREAD

**Issue by edgarswed** [lest/prometheus-rpm#50]
Hello,
looks like another small bug in node_exporter rpm. 

> cat /etc/systemd/system/multi-user.target.wants/node_exporter.service
> \# -*- mode: conf -*-
> 
> [Unit]
> 
> Description=Prometheus exporter for machine metrics, written in Go with pluggable metric collectors.
> Documentation=https://github.com/prometheus/node_exporter
> After=network.target
> 
> 
> [Service]
> 
> EnvironmentFile=-/etc/default/node_exporter
> User=prometheus
> ExecStart=/usr/bin/node_exporter $NODE_**EXPORTER**_EXPORTER_OPTS
> Restart=on-failure
> 
> 
> [Install]
> 
> WantedBy=multi-user.target

> cat /etc/default/node_exporter 
> NODE_EXPORTER_OPTS='some_options_here'

Variable name is different, therefore node_exporter starts, but doesn't apply flags from /etc/default/node_exporter

**Comment by nickb834** [comment]
That's specific to systemd boxes for what it's worth, RH6 using sysv reads it just fine (default needs USER= adding in for eg to get the app to start)

**Comment by lest** [comment]
Thank you for reporting this issue. Fixed in https://github.com/lest/prometheus-rpm/commit/376022024fe7201df0823c072da4cd79beb3caa7.
