### ISSUE TITLE
Sysv init scripts running as none root user fail to start node_exporter (at least)

### ISSUE THREAD

**Issue by nickb834** [lest/prometheus-rpm#51]
The current rpm for sysv init based distros [RedHat|CentOS] 6.x can't start the service due to:

prometheus user has shell set `/sbin/nologin` - a quick workaround without changing shell is to add `su -s /bin/sh` to init script line 24 after ${USER} var:

`su - "${USER}" -s /bin/sh -c "${CMD} &> ${LOGFILE} & echo \$! > ${tmp_pid}"`

However - the prometheus user doesn't have perms to write pid file in `/var/run` nor log file in `/var/log`

I've looked at changing the init script to source `/etc/init.d/functions` and making use of daemon function that will take care of the perms issue:

`source functions; daemon --user=prometheus --pidfile=/var/run/node_exporter.pid /usr/bin/node_exporter`

Not sure of best way forward tbh.......

**Comment by zoonage** [comment]
I would say doing this properly and using the `daemon` function is the correct way to go. I'm surprised that I didn't use `daemon` when I wrote the template file out...

**Comment by ncamx** [comment]
happened to be looking at the same/similar issue on el6. The following version of start() works for me for running node_explorer on centOS6 as non-root

#!/bin/sh

# chkconfig: 2345 60 20
# description: node_exporter

source /etc/init.d/functions

USER=prometheus
NAME=node_exporter
SCRIPT="/usr/bin/${NAME}"
PIDFILE="/var/run/${NAME}.pid"
LOGFILE="/var/log/${NAME}.log"
ENVFILE="/etc/default/${NAME}"

start() {

  if [ -f "${PIDFILE}" ] && kill -0 $(cat "${PIDFILE}") &> /dev/null; then
    echo "${NAME} already running with PID $(cat ${PIDFILE})" >&2
    return 1
  fi

  echo "Starting ${NAME}" >&2
  . "${ENVFILE}"

  daemon --user $USER --pidfile="$PIDFILE" "${SCRIPT} &"  2&> $LOGFILE

  echo `pidof $NAME` > ${PIDFILE}

  echo "${NAME} started with PID $(cat ${PIDFILE})" >&2
  sleep 1
  if [ -f "${PIDFILE}" ] && kill -0 $(cat "${PIDFILE}") &> /dev/null; then
    echo "${NAME} started successfully." >&2
  else
    echo "${NAME} was not started OK"
    return 1
  fi

}

**Comment by ncamx** [comment]
Note, Fix (modified version of the above) delivered as part of [#82](https://github.com/lest/prometheus-rpm/issues/82)
