### ISSUE TITLE
Exporters not updated to last version in the repo.

### ISSUE THREAD

**Issue by fchiorascu** [lest/prometheus-rpm#52]
Hi,

I've checked the repository and I did not find all the versions for the components:
-HAProxy
-Redis
etc

Will you update the repository to all versions for exporters also.

Kind Regards,

**Comment by zoonage** [comment]
Working on this ATM

Redis is hacked in a little bit until https://github.com/oliver006/redis_exporter/issues/173 is fixed
HAproxy is in progress

I can put in updates for requested exporters, but I won't be manually going around updating all of them

**Comment by zoonage** [comment]
@fchiorascu are there any more exporters you want done in particular or can we close this out?

**Comment by fchiorascu** [comment]
- Haproxy
- Elasticsearch
- Redis
- Mongodb
- Memcached
- Consul
- Blackbox Exporter
- MQTT

Thank you very much for your work, really appreciated.

**Comment by karlism** [comment]
Closing this issue as most of the exporters have been updated since then. Merge requests are welcome if there are any other updates or new exporters required.
