### ISSUE TITLE
Add  dnsmasq_exporter

### ISSUE THREAD

**Issue by matthiasantierens** [lest/prometheus-rpm#539]
I would like to add the dnsmasq_exporter, but I am not sure how to add it because it does not have a release.
Go get is also broken atm so I had to build it with `go build .`

Any pointers? 

Thanks in advance for the hard work!

**Comment by karlism** [comment]
@matthiasantierens, we currently do not support building exporters from source (nor we ever plan to), exporter binary release is a requirement to build packages. Best course of action would be to create PR in dnsmasq exporter repository and adjust their GH workflow to release binaries for their exporter.

**Comment by matthiasantierens** [comment]
Can I for now just add it as Source0 ?
