### ISSUE TITLE
packagecloud.io pgp key for node exporter is not valid

### ISSUE THREAD

**Issue by devstek** [lest/prometheus-rpm#541]
Hi,

when installing node_exporter manually via [packagecloud.io](https://packagecloud.io/prometheus-rpm/release) the described gpg key is not valid here: https://packagecloud.io/app/prometheus-rpm/release/gpg 

Needed to install pgp key from https://raw.githubusercontent.com/lest/prometheus-rpm/master/RPM-GPG-KEY-prometheus-rpm additionally to get package installed as stated in readme.md

Please fix https://packagecloud.io/app/prometheus-rpm/release/gpg documentation

**Comment by lest** [comment]
Hi @devstek. There are two different keys:

1) https://packagecloud.io/app/prometheus-rpm/release/gpg - to verify YUM metadata signature

2) https://raw.githubusercontent.com/lest/prometheus-rpm/master/RPM-GPG-KEY-prometheus-rpm - to verify RPM package signature

Unfortunately, we don't control documentation on https://packagecloud.io/app/prometheus-rpm/release/gpg to also include information about the key used to sign RPMs.
