### ISSUE TITLE
Duplicate package in repo

### ISSUE THREAD

**Issue by maartenbeeckmans** [lest/prometheus-rpm#575]
When mirroring the prometheus rpm repository in pulp we are experiencing errors due to a duplicate package.

Pulp is returning the following error:
`A file located at the url https://packagecloud.io/prometheus-rpm/release/el/8/x86_64/prometheus2-2.30.3-1.el8.x86_64.rpm failed validation due to checksum.`

When trying [dralley](https://github.com/dralley) tried downloading it manually with rpmrepo, it is failing with the following error:

![image](https://user-images.githubusercontent.com/22379063/149962027-d4d0980c-ddd5-46b8-8ba0-d0fdcf1522a6.png)

**Comment by dralley** [comment]
In summary there's two different entries in the metadata referring to the same package (same name, epoch, version, release, and arch) and both point to the same file but both have different checksums.  

There should only be one entry for each NEVRA combination is the primary issue, just make sure the old / invalid one isn't there.

**Comment by karlism** [comment]
No idea why 2 identical packages have been published, @lest, can you please manually remove one of them?
https://packagecloud.io/app/prometheus-rpm/release/search?q=prometheus2-2.30

**Comment by maartenbeeckmans** [comment]
Any update on this issue?

**Comment by lest** [comment]
@karlism I missed your comment earlier. I deleted one of them manually via the packagecloud UI.

@maartenbeeckmans can you please check if the issue is resolved?

**Comment by maartenbeeckmans** [comment]
Yes, now it works.

Thx for fixing the issue.
