### ISSUE TITLE
CentOS 8 EOL

### ISSUE THREAD

**Issue by karlism** [lest/prometheus-rpm#584]
@lest, @britcey, looks like CentOS 8 has reached EOL and AppStream repository is no longer working ("CentOS Linux 8 will reach End Of Life (EOL) on December 31st, 2021."):
```
# docker run --rm -i -t ghcr.io/lest/centos-rpm-builder:8 bash
[root@5ab259768a81 rpmbuild]# dnf update -v
Failed to set locale, defaulting to C.UTF-8
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync
DNF version: 4.2.7
cachedir: /var/cache/dnf
repo: downloading from remote: AppStream
CentOS-8 - AppStream                                                                                              17  B/s |  38  B     00:02    
Cannot download 'http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=container': Cannot prepare internal mirrorlist: No URLs in mirrorlist.
Failed to download metadata for repo 'AppStream'
Error: Failed to download metadata for repo 'AppStream'
[root@5ab259768a81 rpmbuild]# curl 'http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=container'
Invalid release/repo/arch combination
```

Any suggestions how to proceed from here? We can either use CentOS Stream or any of other RHEL clones, I've replaced CentOS with Oracle Linux quite successfully at the company currently I'm working for.

Until this is resolved, I guess all our builds will fail.

**Comment by lest** [comment]
@karlism Please correct me if I'm wrong. CentOS Stream 8 is a replacement for CentOS 8, so rebuilding the `centos-rpm-builder` image based on it can be a fix. Am I missing something?

**Comment by karlism** [comment]
@lest, technically CentOS Stream 8 is replacement for CentOS 8, but it deviates from RHEL8 and I'm not sure if it is good idea to build packages on OS that might be significantly different from other RHEL8 clones.

**Comment by lest** [comment]
I pushed `lest/centos-rpm-builder:stream8` and `ghcr.io/lest/centos-rpm-builder:stream8` so we can try using them temporarily. I also want to build images based on Oracle Linux 8 so we can test it too.

**Comment by lest** [comment]
I also pushed `lest/centos-rpm-builder:oracle8` and `ghcr.io/lest/centos-rpm-builder:oracle8` based on Oracle Linux 8. I guess we can try either it or the CentOS Stream 8 one. I'll try to dedicate some time this week for testing. Please feel free to experiment with them so we can get builds running.

**Comment by karlism** [comment]
@lest, thanks, just tried building with OL8 image, looks good, will try CentOS 8 Stream next.

**Comment by karlism** [comment]
@lest, everything builds fine also with CentOS 8 Stream images.

There is actually one issue with JMX exporter, but it's an issue in spec file that I will fix shortly.

**Comment by britcey** [comment]
Thanks for jumping on this issue;

what's the path forward - produce both Stream & OL8 images?  We've been dragging our feet but I think we're headed to OL8 internally.

**Comment by karlism** [comment]
Not sure if it makes much sense to build packages on multiple distributions, our RPMs are basically statically linked binaries with standard systemd/defaults files, they should work on any distribution that supports RPMs and systemd.

**Comment by k0ste** [comment]
@lest it is possible to resolve this issue? Actually we stale for a weeks, even for CentOS 7 builds

**Comment by lest** [comment]
@karlism @britcey I updated the build process to use OL8 for building EL8 RPMs. It seems to be working good now so we can start updating and merging pull requests.
