### ISSUE TITLE
snmp_exporter: 0.14.0 is out.

### ISSUE THREAD

**Issue by k0ste** [lest/prometheus-rpm#66]
https://github.com/prometheus/snmp_exporter/releases/tag/v0.14.0

**Comment by lest** [comment]
Hi @k0ste,

I updated the snmp_exporter package to the latest version.

The build process is automated on Travis CI, so it's enough to have a pull request (like this one https://github.com/lest/prometheus-rpm/pull/72) merged to have the updated package available in the repository.

Feel free to submit a pull request in future to get access to updated packages faster.

Cheers,
Sergey

**Comment by k0ste** [comment]
@lest, got it.
Thank you.
