### ISSUE TITLE
reposync Error: jmx_exporter-0.12.0-1.el8.noarch.rpm' is outside of download path

### ISSUE THREAD

**Issue by zengyijian916** [lest/prometheus-rpm#676]
**Issue:**
[root@LocalCentOS8 ~]# reposync --repoid=prometheus -p /var/www/html/repos/prometheus
prometheus                                                        309  B/s | 833  B     00:02    
Error: Download target '/var/www/html/repos/prometheus/noarch/jmx_exporter-0.12.0-1.el8.noarch.rpm' is outside of download path '/var/www/html/repos/prometheus/prometheus'.
[root@LocalCentOS8 ~]
**Procedure:**
https://packagecloud.io/prometheus-rpm/release/mirror

[root@LocalCentOS8 ~]# cat /etc/yum.repos.d/prometheus.repo 
[prometheus]
name=prometheus
baseurl=https://packagecloud.io/prometheus-rpm/release/el/8/$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/prometheus-rpm/release/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300

[prometheus-rpm_release-source]
name=prometheus-rpm_release-source
baseurl=https://packagecloud.io/prometheus-rpm/release/el/8/SRPMS
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/prometheus-rpm/release/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
[root@LocalCentOS8 ~]#

**Comment by zengyijian916** [comment]
Please help. how to fix this issue?

**Comment by karlism** [comment]
Looks like this is known reposync issue: https://bugzilla.redhat.com/show_bug.cgi?id=1898089

**Comment by zengyijian916** [comment]
I think this is not due to that known issue. it's due to there is another directory named "noarch" in this repo URL.  All of the RPMs should be under one directory to avoid issues. hope this could fix later. just need `mv noarch/* ./` should work
