### ISSUE TITLE
Packaging question - thanos?

### ISSUE THREAD

**Issue by britcey** [lest/prometheus-rpm#75]
This is not exactly an issue, just some questions:

1) Any interest in adding Thanos?  https://github.com/improbable-eng/thanos

2) If 'yes', a packaging question:

Thanos is really a variety of components - a single 'thanos' binary with various subcommands:

'thanos sidecar'
'thanos store'
'thanos query'
'thanos compact'

etc.

What makes more sense:

1) a single 'thanos' package, with thanos_sidecar, thanos_store, thanos_query, etc. service and default files 

2) a 'thanos-base' package with just the binary and 'thanos-sidecar', 'thanos-store', etc. packages that just contain service & default files?

**Comment by lest** [comment]
Hi @britcey,

I don't mind having it added.

I think it's better to have a single package with the binary and all the services. Users will be able to enable only services they want to use.

Cheers,
Sergey

**Comment by britcey** [comment]
Sounds good (and easier for me :-).

PR to come.
