### ISSUE TITLE
sql_exporter abondoned

### ISSUE THREAD

**Issue by bastischubert** [lest/prometheus-rpm#756]
HI there, 

the packaged sql_exporter (https://github.com/free/sql_exporter)  seems abondone, but there is a fork on https://github.com/burningalchemist/sql_exporter which seems to be the most active (eg. used by the grafana agent ;) ) - you might want to switch to that fork.

**Comment by karlism** [comment]
@bastischubert, thanks for letting us know, SQL exporter package has been updated.
