### ISSUE TITLE
Support Debain packages

### ISSUE THREAD

**Issue by zoonage** [lest/prometheus-rpm#84]
It would be good if we could support systems that use DPKG as well as RPM based systems.

Proposed solution: We could use alien to convert the outputted RPMs to DPKG format, however I don't know how reliable that is.

Another solution would be to template the DPKG builds in a similar way to what we do with RPMs, but that is more work

@lest Would this need any changes on the Package Cloud side to support .debs in the same repo?

**Comment by lest** [comment]
Packagecloud supports having both RPMs and DEBs in the same repo. Using alien can be a good solution if it's reliable enough.

**Comment by zoonage** [comment]
I think one of the issues we are going to have is keeping the same script working between two OSs, I just did a quick check with the kafka RPM and alien could not convert it straight out.

**Comment by vhaidamaka** [comment]
@zoonage Most of prometheus packages are available in the debian/sid.
Take a look [salsa.debian.org](https://salsa.debian.org/go-team/packages?utf8=%E2%9C%93&filter=prometheus)

**Comment by zoonage** [comment]
@vhaidamaka thanks, I'll close this out
