### ISSUE TITLE
Duplicate package prometheus2-2.47.1-1.el9.x86_64.rpm

### ISSUE THREAD

**Issue by seventytwo** [lest/prometheus-rpm#885]
When synchronising repository from packagecloud I'm getting the following error:
```
(194/195): prometheus2-2.47.1-1.el9.x86_64.rpm                                                            26 MB/s |  38 MB     00:01                                                                                                                                              
[MIRROR] prometheus2-2.47.1-1.el9.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 599def62645c4ef71a746397c4415b7a9af310e8(sha1)  Expected: ee47119afbbd1b203c60a5e5ecc0b80e96c11e13(sha1)                                                            

```
There seems to be two rpms (and two entries in the repodata), one with each of the sums mentioned in the error.  

https://packagecloud.io/app/prometheus-rpm/release/search?q=prometheus2-2.47.1-1&filter=all&filter=all&dist=el%2F9

Possibly the same issue as described on [575](https://github.com/lest/prometheus-rpm/issues/575)

(side note, thanks for packaging this up in the first place).

**Comment by karlism** [comment]
@seventytwo, indeed it looks to be the same issue as in https://github.com/lest/prometheus-rpm/issues/575

@lest, can you please manually remove that package?

**Comment by lest** [comment]
@seventytwo I deleted one of the packages. Please let me know if it's fixed.

**Comment by seventytwo** [comment]
> @seventytwo I deleted one of the packages. Please let me know if it's fixed.

Yes that's sorted it, synchronised fine now.  Thanks.
