### ISSUE TITLE
mongodb_exporter version issue on packagecloud.io

### ISSUE THREAD

**Issue by SimBou** [lest/prometheus-rpm#949]
Hi,
"mongodb_exporter-2.37.0-1" has been build and push 1 year ago but this version doesn't exist on https://github.com/percona/mongodb_exporter
Is it possible to remove the rpm from packageclouid.io repository ?
Has the version is greater than the real latest one, installation or update doesn't use the good one...
Regards

**Comment by karlism** [comment]
@lest, can you please take care of this?

**Comment by SimBou** [comment]
Hello, do you have any updates on this issue ?
Regards

**Comment by SimBou** [comment]
Thank you very much
